<?php

declare(strict_types=1);

namespace Ions\commands;

use Closure;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Ions\Bundles\Path;
use Ions\Support\Storage;

/**
 * config:cache — merge every config/*.php file (the same set the kernel's
 * captureConfig() reads) into a single var/cache/config.php returning the
 * full array. When APP_DEBUG is off and the file exists, boot loads it and
 * skips reading/`include`-ing each config file individually.
 *
 * Note: env() calls inside config files are evaluated at cache-build time,
 * so the cached values are frozen until config:cache is re-run.
 *
 * Closures cannot be exported to PHP source; the command fails loudly and
 * names the offending config key.
 */
class ConfigCacheCommand extends Command
{
    protected $signature = 'config:cache';

    protected $description = 'Merge all config files into var/cache/config.php for fast boot';

    public function handle(): int
    {
        $configs = [];
        foreach (Storage::files(Path::config()) as $configFile) {
            $configs[File::name($configFile)] = include $configFile;
        }

        $closureKey = $this->findClosure($configs, '');
        if ($closureKey !== null) {
            $this->error(sprintf(
                "Config key '%s' contains a Closure and cannot be cached. " .
                'Replace it with a serializable value (or resolve it in a provider), then re-run config:cache.',
                $closureKey
            ));

            return self::FAILURE;
        }

        $dir = Path::cache('');
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            $this->error("Unable to create cache directory: {$dir}");

            return self::FAILURE;
        }

        $file = Path::cache('config.php');
        file_put_contents(
            $file,
            "<?php\n\n// Generated by config:cache — do not edit. Run config:clear to remove.\n\nreturn "
            . var_export($configs, true) . ";\n"
        );

        $this->info(sprintf('Config cache written (%d files merged) -> %s', count($configs), $file));

        return self::SUCCESS;
    }

    /**
     * Depth-first search for a Closure anywhere in the merged config tree.
     *
     * @return string|null Dot-path of the first Closure found, or null.
     */
    private function findClosure(mixed $value, string $path): ?string
    {
        if ($value instanceof Closure) {
            return $path;
        }

        if (is_array($value)) {
            foreach ($value as $key => $item) {
                $found = $this->findClosure($item, $path === '' ? (string) $key : $path . '.' . $key);
                if ($found !== null) {
                    return $found;
                }
            }
        }

        return null;
    }
}
