<?php

declare(strict_types=1);

namespace Ions\commands;

use Closure;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Ions\Bundles\Path;
use Ions\Support\Storage;

/**
 * config:cache — merge every config/*.php file (the same set the kernel's
 * captureConfig() reads) into a single var/cache/config.php returning the
 * full array. When APP_DEBUG is off and the file exists, boot loads it and
 * skips reading/`include`-ing each config file individually.
 *
 * Note: env() calls inside config files are evaluated at cache-build time,
 * so the cached values are frozen until config:cache is re-run.
 *
 * Closures cannot be exported to PHP source; the command fails loudly and
 * names the offending config key.
 */
class ConfigCacheCommand extends Command
{
    protected $signature = 'config:cache';

    protected $description = 'Merge all config files into var/cache/config.php for fast boot';

    public function handle(): int
    {
        // Warn when caching under debug mode — production will then read debug
        // env values frozen into the cache file until config:cache is re-run.
        if (env('APP_DEBUG', false)) {
            $this->warn(
                'Warning: config:cache was run with APP_DEBUG=true. '
                . 'The cache will contain debug-mode env values; production will read these '
                . 'until config:cache is re-run in a production environment.'
            );
        }

        $configs = [];
        foreach (Storage::files(Path::config()) as $configFile) {
            $configs[File::name($configFile)] = include $configFile;
        }

        $unsafeKey = $this->findUnsafeValue($configs, '');
        if ($unsafeKey !== null) {
            [$dotPath, $reason] = $unsafeKey;
            $this->error(sprintf(
                "Config key '%s' contains a %s and cannot be cached. " .
                'Replace it with a serializable value (or resolve it in a provider), then re-run config:cache.',
                $dotPath,
                $reason
            ));

            return self::FAILURE;
        }

        $dir = Path::cache('');
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            $this->error("Unable to create cache directory: {$dir}");

            return self::FAILURE;
        }

        $file = Path::cache('config.php');
        file_put_contents(
            $file,
            "<?php\n\n// Generated by config:cache — do not edit. Run config:clear to remove.\n\nreturn "
            . var_export($configs, true) . ";\n"
        );

        $this->info(sprintf('Config cache written (%d files merged) -> %s', count($configs), $file));

        return self::SUCCESS;
    }

    /**
     * Depth-first search for a value that cannot be safely exported by var_export():
     *   - Closures (cannot be exported at all)
     *   - Objects that do not implement __set_state() (var_export would produce
     *     ClassName::__set_state([...]) which fatals at require-time when the
     *     method is absent, with no useful context for the developer)
     *
     * @return array{string, string}|null Tuple of [dot-path, human-readable reason], or null when safe.
     */
    private function findUnsafeValue(mixed $value, string $path): ?array
    {
        if ($value instanceof Closure) {
            return [$path, 'Closure'];
        }

        if (is_object($value) && !method_exists($value, '__set_state')) {
            return [$path, 'object of class ' . get_class($value) . ' (no __set_state)'];
        }

        if (is_array($value)) {
            foreach ($value as $key => $item) {
                $child = $path === '' ? (string) $key : $path . '.' . $key;
                $found = $this->findUnsafeValue($item, $child);
                if ($found !== null) {
                    return $found;
                }
            }
        }

        return null;
    }
}
