<?php

declare(strict_types=1);

namespace Ions\commands;

use Illuminate\Console\Command;
use Ions\Bundles\Path;
use Ions\Foundation\Discovery;

/**
 * discover:cache — run the live provider discovery (framework defaults +
 * composer extra.ions.providers + host {src|app}/Providers scan) once and
 * freeze the merged list into var/cache/providers.php. When APP_DEBUG is off
 * and the file exists, boot loads it with a single require and skips every
 * scan (the Laravel packages.php pattern).
 *
 * The cache never invalidates itself: re-run discover:cache (or `optimize`,
 * which includes it) after composer install/update and after adding or
 * removing providers. Setting an explicit `app.providers` list remains the
 * zero-scan alternative that needs no cache at all.
 */
class DiscoverCacheCommand extends Command
{
    protected $signature = 'discover:cache';

    protected $description = 'Cache the discovered provider list into var/cache/providers.php for fast boot';

    public function handle(): int
    {
        // Warn when caching under debug mode — the cache is ignored while
        // APP_DEBUG is on, but production will load this exact list (built
        // from the debug environment) until discover:cache is re-run.
        if (env('APP_DEBUG', false)) {
            $this->warn(
                'Warning: discover:cache was run with APP_DEBUG=true. '
                . 'The cache is ignored while debugging, but production (APP_DEBUG=false) will '
                . 'load this provider list until discover:cache is re-run.'
            );
        }

        $providers = Discovery::providers();

        $dir = Path::cache('');
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            $this->error("Unable to create cache directory: {$dir}");

            return self::FAILURE;
        }

        $file = Path::cache('providers.php');
        $written = @file_put_contents(
            $file,
            "<?php\n\n// Generated by discover:cache — do not edit. Run discover:clear to remove.\n"
            . "// Re-run discover:cache (or optimize) after composer install/update or provider changes.\n\nreturn "
            . var_export($providers, true) . ";\n"
        );

        if ($written === false) {
            $this->error("Unable to write provider cache: {$file}");

            return self::FAILURE;
        }

        foreach ($providers as $provider) {
            $this->line('  ' . $provider);
        }
        $this->info(sprintf('Provider cache written (%d providers) -> %s', count($providers), $file));

        return self::SUCCESS;
    }
}
