<?php

declare(strict_types=1);

namespace Ions\commands;

use Illuminate\Console\Command;
use Ions\Bundles\Path;
use ReflectionClass;

/**
 * preload:generate — emit var/cache/preload.php, an opcache.preload file that
 * compiles the framework's hot classes (kernel, container, providers,
 * middleware, routing, request/response) into opcache at server start.
 *
 * Optional: point your php.ini at it —
 *   opcache.preload=/path/to/host/var/cache/preload.php
 *   opcache.preload_user=www-data
 */
class PreloadGenerateCommand extends Command
{
    protected $signature = 'preload:generate';

    protected $description = 'Generate var/cache/preload.php (opcache.preload file) for the framework hot path';

    /**
     * Curated hot-path classes. Order is irrelevant — opcache_compile_file()
     * compiles each file independently.
     *
     * @return list<class-string>
     */
    private function hotClasses(): array
    {
        return [
            // Foundation
            \Ions\Foundation\Kernel::class,
            \Ions\Foundation\Config::class,
            \Ions\Foundation\Singleton::class,
            // Container + providers
            \Ions\Container\Container::class,
            \Ions\Container\ServiceProvider::class,
            \Ions\Providers\ConfigProvider::class,
            \Ions\Providers\FilesystemProvider::class,
            \Ions\Providers\SessionProvider::class,
            \Ions\Providers\DatabaseProvider::class,
            \Ions\Providers\CacheProvider::class,
            \Ions\Providers\EventProvider::class,
            \Ions\Providers\QueueProvider::class,
            \Ions\Providers\AuthProvider::class,
            \Ions\Providers\MailProvider::class,
            \Ions\Providers\ViewProvider::class,
            // Middleware pipeline
            \Ions\Http\Middleware\MiddlewareInterface::class,
            \Ions\Http\Middleware\Pipeline::class,
            \Ions\Http\Middleware\ControllerDispatcher::class,
            \Ions\Http\Middleware\TrustedHostMiddleware::class,
            \Ions\Http\Middleware\SecurityHeadersMiddleware::class,
            \Ions\Http\Middleware\CorsMiddleware::class,
            \Ions\Http\Middleware\CsrfMiddleware::class,
            \Ions\Http\Middleware\StartSessionMiddleware::class,
            \Ions\Http\Middleware\AuthMiddleware::class,
            \Ions\Http\Middleware\RateLimitMiddleware::class,
            \Ions\Http\ExceptionHandler::class,
            \Ions\Http\Json::class,
            // Request / response / session
            \Ions\Support\Request::class,
            \Ions\Support\Response::class,
            \Ions\Support\JsonResponse::class,
            \Ions\Session\SessionManager::class,
            \Ions\Security\SecurityHeaders::class,
            // Path + routing
            \Ions\Bundles\Path::class,
            \Ions\Bundles\Route::class,
            \Ions\Bundles\AttributeRouteControllerLoader::class,
            \Symfony\Component\Routing\RequestContext::class,
            \Symfony\Component\Routing\Matcher\CompiledUrlMatcher::class,
            \Symfony\Component\Routing\Matcher\UrlMatcher::class,
            \Symfony\Component\Routing\RouteCollection::class,
            \Symfony\Component\Routing\Route::class,
            \Symfony\Component\HttpFoundation\Request::class,
            \Symfony\Component\HttpFoundation\Response::class,
        ];
    }

    public function handle(): int
    {
        $files = [];
        foreach ($this->hotClasses() as $class) {
            $file = (new ReflectionClass($class))->getFileName();
            if (is_string($file) && $file !== '') {
                $files[$file] = true;
            }
        }

        $dir = Path::cache('');
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            $this->error("Unable to create cache directory: {$dir}");

            return self::FAILURE;
        }

        $list = '';
        foreach (array_keys($files) as $file) {
            $list .= '    ' . var_export($file, true) . ",\n";
        }

        $content = <<<PHP
<?php

// Generated by preload:generate — opcache.preload file for the Ions hot path.
// php.ini: opcache.preload={$dir}preload.php

if (!function_exists('opcache_compile_file')) {
    return;
}

\$files = [
{$list}];

foreach (\$files as \$file) {
    if (is_file(\$file)) {
        @opcache_compile_file(\$file);
    }
}

PHP;

        $target = Path::cache('preload.php');
        file_put_contents($target, $content);

        $this->info(sprintf('Preload file written (%d files) -> %s', count($files), $target));

        return self::SUCCESS;
    }
}
